#
# Copyright 2022 Kontain Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Dockerfile for tensor flow inferencing test app in kontainer

FROM test-app as app

FROM kontainapp/runenv-dynamic-python
# ARG UID=1001
# ARG GID=117
ARG USERNAME=appuser
COPY --from=app /etc/passwd /etc/
COPY --from=app /etc/pki /etc/pki/
COPY --from=app /etc/ssl /etc/ssl/
# USER appuser
ENV HOME /home/$USERNAME
WORKDIR /mnt
# COPY --chown=$UID:$GID run.sh run_snap.sh /
# COPY --from=app --chown=$UID:$GID $HOME $HOME/
COPY run.sh run_snap.sh /
COPY --from=app $HOME $HOME/
COPY tmp/kmsnap $HOME/
CMD [ "/home/appuser/kmsnap" ]
